[theme]
base            = "dark"
primaryColor    = "#e63946"
backgroundColor = "#10131a"
secondaryBackgroundColor = "#191b23"
textColor       = "#e3e4ea"
font            = "sans serif"

[server]
headless           = true
enableCORS         = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
